#!/usr/bin/env bash
# orc installer — builds the tool and installs a version-independent `orc` launcher.
# Safe to re-run. Run from inside a cloned orc repo:  ./install.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.orc"

echo "orc installer"
echo "  repo: $REPO_DIR"

# 1. Require Node >= 20, and capture its absolute path so the launcher is nvm-proof.
if ! command -v node >/dev/null 2>&1; then
  echo "Error: node not found. Install Node >= 20 (e.g. via nvm) and re-run." >&2
  exit 1
fi
NODE_BIN="$(command -v node)"
NODE_BIN="$(cd "$(dirname "$NODE_BIN")" && pwd)/$(basename "$NODE_BIN")"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
if [ "$NODE_MAJOR" -lt 20 ]; then
  echo "Error: Node >= 20 required (found $(node -v))." >&2
  exit 1
fi
echo "  node: $NODE_BIN ($(node -v))"

# 2. Install deps + build (the package's prepare script builds automatically).
echo "Installing dependencies and building..."
( cd "$REPO_DIR" && npm install )
[ -f "$REPO_DIR/dist/index.js" ] || ( cd "$REPO_DIR" && npm run build )

# 3. Install the launcher.
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/orc" <<EOF
#!/bin/sh
# orc launcher (generated by install.sh) — pinned Node so it survives nvm switches.
exec "$NODE_BIN" "$REPO_DIR/dist/index.js" "\$@"
EOF
chmod +x "$BIN_DIR/orc"
echo "Installed launcher: $BIN_DIR/orc"

# 4. Ensure ~/.local/bin is on PATH.
case ":$PATH:" in
  *":$BIN_DIR:"*)
    PATH_OK=1 ;;
  *)
    PATH_OK=0
    case "${SHELL:-}" in
      */zsh)  RC="$HOME/.zshrc" ;;
      */bash) RC="$HOME/.bashrc" ;;
      *)      RC="$HOME/.profile" ;;
    esac
    printf '\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$RC"
    echo "Added $BIN_DIR to PATH in $RC"
    ;;
esac

# 5. Scaffold the global config if missing.
if [ ! -f "$CONFIG_DIR/config.json" ]; then
  mkdir -p "$CONFIG_DIR"
  cp "$REPO_DIR/examples/config.json" "$CONFIG_DIR/config.json"
  echo "Created $CONFIG_DIR/config.json from example — edit it with your project paths."
else
  echo "Config already exists: $CONFIG_DIR/config.json (left unchanged)."
fi

echo ""
echo "Done. Next steps:"
echo "  1) Edit ~/.orc/config.json  (set projects[].path to your repos)"
echo "  2) Copy examples/mobile-CLAUDE.md into each project's CLAUDE.md"
if [ "${PATH_OK:-1}" -eq 0 ]; then
  echo "  3) Open a NEW terminal (PATH was updated), then run:  orc"
else
  echo "  3) Run:  orc     (in a new shell, or run 'rehash' first)"
fi
