#!/usr/bin/env bash
# orc installer — builds the release binary and installs an `orc` launcher.
# Safe to re-run. Run from inside a cloned orc repo:  ./install.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.orc"

echo "orc installer"
echo "  repo: $REPO_DIR"

# 1. Require a Rust toolchain.
if ! command -v cargo >/dev/null 2>&1; then
  echo "Error: cargo not found. Install Rust (https://rustup.rs) and re-run." >&2
  exit 1
fi
echo "  cargo: $(command -v cargo) ($(cargo --version))"

# 2. Build the release binary. Always rebuild so a re-run after pulling new code recompiles.
echo "Building (cargo build --release)..."
cd "$REPO_DIR"
cargo build --release
BIN_SRC="$REPO_DIR/target/release/orc"
if [ ! -x "$BIN_SRC" ]; then
  echo "Error: expected binary not found at $BIN_SRC after build." >&2
  exit 1
fi

# 3. Install the launcher.
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/orc" <<EOF
#!/bin/sh
# orc launcher (generated by install.sh).
exec "$BIN_SRC" "\$@"
EOF
chmod +x "$BIN_DIR/orc"
echo "Installed launcher: $BIN_DIR/orc"

# 4. Ensure ~/.local/bin is on PATH.
case ":$PATH:" in
  *":$BIN_DIR:"*)
    PATH_OK=1 ;;
  *)
    PATH_OK=0
    case "${SHELL:-}" in
      */zsh)  RC="$HOME/.zshrc" ;;
      */bash) RC="$HOME/.bashrc" ;;
      *)      RC="$HOME/.profile" ;;
    esac
    printf '\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$RC"
    echo "Added $BIN_DIR to PATH in $RC"
    ;;
esac

# 5. Report config status — the installer NEVER writes the config; you create/edit it yourself.
if [ -f "$CONFIG_DIR/config.json" ]; then
  echo "Config found: $CONFIG_DIR/config.json (left untouched)."
else
  echo "No config yet: create $CONFIG_DIR/config.json yourself (see examples/config.json)."
fi

echo ""
echo "Done. Next steps (all manual):"
echo "  1) Create/edit ~/.orc/config.json yourself  (see $REPO_DIR/examples/config.json)"
echo "  2) In orc, press 'p' to install a CLAUDE.md into a project (optional)"
if [ "${PATH_OK:-1}" -eq 0 ]; then
  echo "  3) Open a NEW terminal (PATH was updated), then run:  orc"
else
  echo "  3) Run:  orc     (in a new shell, or run 'rehash' first)"
fi
